services:
  db:
    container_name: psql_reminder
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: ${DBUserName}
      POSTGRES_PASSWORD: ${DBPassword}
      POSTGRES_DB: ${DBName}
    volumes:
      - db-data:/var/lib/postgresql/data
    
  backend:
    build: .
    container_name: backend_reminder
    
volumes:
  db-data:
